run:
  timeout: 5m
  tests: false

linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - dupword
    - funlen
    - err113
    - gochecknoglobals
    - gocognit
    - gofumpt
    - lll
    - varnamelen

    - tenv # deprecated